#!/bin/bash

export cmdpath=$GOPATH/src/github.com/alphazero/gart/cmd
export outfile=$cmdpath/gart-debug
go build \
	-ldflags="-X github.com/alphazero/gart/system.DebugFlag=true" \
	-o $outfile \
	$cmdpath/*.go

chmod +x $outfile
